### ISSUE TITLE
Plan and Default setting of sass

### ISSUE THREAD

**Issue by ImHyeYoung** [zeki-team/zeki#2]
-Plan a specific feature and  Design.
-The default setting of sass (partials ,mixin, variable...)

**Comment by conrad-ko** [comment]
@ImHyeYoung 
Zeki V 0.0.1 is the February 1st.
In Progress label is not it should be excluded ?

I think that items must be broken down .
ex) 
-zeki-table option plan implementation specific features
-zeki-table design, implementation plan
-zeki-table specifies the basic functions
-zeki-table sass basic design guides written
-zeki-table design to create the mark -up
-zeki-table function implementation (scroll?)
